---
ceph_rbd_namespace: "ceph-csi-rbd"
ceph_user_id: "admin"
ceph_cluster_id: "7c245ed6-0cd9-440e-887b-d9fd402c8470"
ceph_monitors:
  - "10.1.2.11:6789"
  - "10.1.2.12:6789"
  - "10.1.2.13:6789"
ceph_wait_for_pods_to_be_ready: true
