roles: []

collections:
  - name: "community.general"
    version: "6.1.0"

  - name: "ansible.posix"
    version: "1.5.2"

  - name: "kubernetes.core"
    version: "2.4.0"

  - name: https://github.com/kubernetes-sigs/kubespray
    type: git
    version: v2.22.1
